version: '3.2'
services:
  # ---------------------------------------------
  # Example of AIS ingestor
  # ---------------------------------------------
  ais_ingestor:
    # Consumes encoded AIS from rabbit and returns decoded AIS to rabbit.
    hostname: ${PROJECT_NAME}_ais_mover
    build:
      context: ./build/ais_i_mov
      dockerfile: Dockerfile
    env_file:
      - .env  #This both the docker-compose env file (to set ports names, image tags etc) and the internal container config (handles passwords, ports to connect to etc.)
    volumes:
      - /etc/localtime:/etc/localtime:ro #This is useful in Linux, doesn't work on Windows. 
      - ${MOUNT_LOG_DIR}:${LOG_DIR}
    command: python /usr/local/ais_i_mov/main.py  -ll 'INFO' 
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m 
